async function Module(moduleArg={}){var moduleRtn;var n=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:b}=await import("node:module");var require=b(import.meta.url)}var da=(b,a)=>{throw a;},ea=import.meta.url,fa="",ha,ia;
if(ca){var fs=require("node:fs");ea.startsWith("file:")&&(fa=require("node:path").dirname(require("node:url").fileURLToPath(ea))+"/");ia=b=>{b=ja(b)?new URL(b):b;return fs.readFileSync(b)};ha=async b=>{b=ja(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2);da=(b,a)=>{process.exitCode=b;throw a;}}else if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ha=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);
var q=console.error.bind(console),u,ka=!1,la,ja=b=>b.startsWith("file://"),ma,na,w,x,y,z,A,D,oa,pa,qa,ra,sa=!1;function ta(){var b=ua.buffer;w=new Int8Array(b);y=new Int16Array(b);x=new Uint8Array(b);z=new Uint16Array(b);A=new Int32Array(b);D=new Uint32Array(b);oa=new Float32Array(b);pa=new Float64Array(b);qa=new BigInt64Array(b);ra=new BigUint64Array(b)}
function va(b){n.onAbort?.(b);b="Aborted("+b+")";q(b);ka=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");na?.(b);throw b;}var wa;async function xa(b){if(!u)try{var a=await ha(b);return new Uint8Array(a)}catch{}if(b==wa&&u)b=new Uint8Array(u);else if(ia)b=ia(b);else throw"both async and sync fetching of the wasm failed";return b}
async function ya(b,a){try{var c=await xa(b);return await WebAssembly.instantiate(c,a)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),va(d)}}async function za(b){var a=wa;if(!u&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return ya(a,b)}
class Aa{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}var Ba=b=>{for(;0<b.length;)b.shift()(n)},Ca=[],Da=[],Ea=()=>{var b=n.preRun.shift();Da.push(b)},Fa=!0,Ga=[],Ha=0,E=0;class Ia{constructor(b){this.Ua=b;this.va=b-24}}
var Ka=b=>{var a=E;if(!a)return F(0),0;var c=new Ia(a);D[c.va+16>>2]=a;var d=D[c.va+4>>2];if(!d)return F(0),a;for(var e of b){if(0===e||e===d)break;if(Ja(e,d,c.va+16))return F(e),a}F(d);return a},La=(b,a)=>Object.defineProperty(a,"name",{value:b}),Ma=[],G=[0,1,,1,null,1,!0,1,!1,1],H=class extends Error{constructor(b){super(b);this.name="BindingError"}},Na=b=>{throw new H(b);},J=b=>{if(!b)throw new H(`Cannot use deleted val. handle = ${b}`);return G[b]},K=b=>{switch(b){case void 0:return 2;case null:return 4;
case !0:return 6;case !1:return 8;default:const a=Ma.pop()||G.length;G[a]=b;G[a+1]=1;return a}};class Oa extends Error{}
var M=b=>{for(var a="";;){var c=x[b++];if(!c)return a;a+=String.fromCharCode(c)}},Pa={},Qa=(b,a)=>{if(void 0===a)throw new H("ptr should not be undefined");for(;b.Aa;)a=b.Ma(a),b=b.Aa;return a},N={},Sa=b=>{b=Ra(b);var a=M(b);O(b);return a},Ta=(b,a)=>{var c=N[b];if(void 0===c)throw b=`${a} has unknown type ${Sa(b)}`,new H(b);return c},Ua=()=>{},Wa=!1,Q=b=>{if(!globalThis.FinalizationRegistry)return Q=a=>a,b;Wa=new FinalizationRegistry(a=>{a=a.ua;--a.count.value;0===a.count.value&&(a.Ca?a.Fa.Ha(a.Ca):
a.ya.wa.Ha(a.va))});Q=a=>{var c=a.ua;c.Ca&&Wa.register(a,{ua:c},a);return a};Ua=a=>{Wa.unregister(a)};return Q(b)},Xa={},Ya=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function Za(b){return this.xa(D[b>>2])}
var R={},$a={},ab=class extends Error{constructor(b){super(b);this.name="InternalError"}},T=(b,a,c)=>{function d(g){g=c(g);if(g.length!==b.length)throw new ab("Mismatched type converter count");for(var l=0;l<b.length;++l)S(b[l],g[l])}b.forEach(g=>$a[g]=a);var e=Array(a.length),f=[],h=0;for(let [g,l]of a.entries())N.hasOwnProperty(l)?e[g]=N[l]:(f.push(l),R.hasOwnProperty(l)||(R[l]=[]),R[l].push(()=>{e[g]=N[l];++h;h===f.length&&d(e)}));0===f.length&&d(e)};
function bb(b,a,c={}){var d=a.name;if(!b)throw new H(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(b)){if(c.jb)return;throw new H(`Cannot register type '${d}' twice`);}N[b]=a;delete $a[b];R.hasOwnProperty(b)&&(a=R[b],delete R[b],a.forEach(e=>e()))}function S(b,a,c={}){return bb(b,a,c)}
var cb=(b,a,c)=>{switch(a){case 1:return c?d=>w[d]:d=>x[d];case 2:return c?d=>y[d>>1]:d=>z[d>>1];case 4:return c?d=>A[d>>2]:d=>D[d>>2];case 8:return c?d=>qa[d>>3]:d=>ra[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},db=b=>{throw new H(b.ua.ya.wa.name+" instance already deleted");},eb=[];function fb(){}
var gb={},hb=(b,a,c)=>{if(void 0===b[a].Ea){var d=b[a];b[a]=function(...e){if(!b[a].Ea.hasOwnProperty(e.length))throw new H(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].Ea})!`);return b[a].Ea[e.length].apply(this,e)};b[a].Ea=[];b[a].Ea[d.Ia]=d}},ib=(b,a)=>{if(n.hasOwnProperty(b))throw new H(`Cannot register public name '${b}' twice`);n[b]=a;n[b].Ia=void 0},jb=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:
b};function kb(b,a,c,d,e,f,h,g){this.name=b;this.constructor=a;this.Ga=c;this.Ha=d;this.Aa=e;this.eb=f;this.Ma=h;this.bb=g;this.Xa=[]}var lb=(b,a,c)=>{for(;a!==c;){if(!a.Ma)throw new H(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.Ma(b);a=a.Aa}return b},mb=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function nb(b,a){if(null===a){if(this.Qa)throw new H(`null is not a valid ${this.name}`);return 0}if(!a.ua)throw new H(`Cannot pass "${mb(a)}" as a ${this.name}`);if(!a.ua.va)throw new H(`Cannot pass deleted object as a pointer of type ${this.name}`);return lb(a.ua.va,a.ua.ya.wa,this.wa)}
function ob(b,a){if(null===a){if(this.Qa)throw new H(`null is not a valid ${this.name}`);if(this.Pa){var c=this.Sa();null!==b&&b.push(this.Ha,c);return c}return 0}if(!a||!a.ua)throw new H(`Cannot pass "${mb(a)}" as a ${this.name}`);if(!a.ua.va)throw new H(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Oa&&a.ua.ya.Oa)throw new H(`Cannot convert argument of type ${a.ua.Fa?a.ua.Fa.name:a.ua.ya.name} to parameter type ${this.name}`);c=lb(a.ua.va,a.ua.ya.wa,this.wa);if(this.Pa){if(void 0===
a.ua.Ca)throw new H("Passing raw pointer to smart pointer is illegal");switch(this.pb){case 0:if(a.ua.Fa===this)c=a.ua.Ca;else throw new H(`Cannot convert argument of type ${a.ua.Fa?a.ua.Fa.name:a.ua.ya.name} to parameter type ${this.name}`);break;case 1:c=a.ua.Ca;break;case 2:if(a.ua.Fa===this)c=a.ua.Ca;else{var d=a.clone();c=this.lb(c,K(()=>d["delete"]()));null!==b&&b.push(this.Ha,c)}break;default:throw new H("Unsupported sharing policy");}}return c}
function pb(b,a){if(null===a){if(this.Qa)throw new H(`null is not a valid ${this.name}`);return 0}if(!a.ua)throw new H(`Cannot pass "${mb(a)}" as a ${this.name}`);if(!a.ua.va)throw new H(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.ua.ya.Oa)throw new H(`Cannot convert argument of type ${a.ua.ya.name} to parameter type ${this.name}`);return lb(a.ua.va,a.ua.ya.wa,this.wa)}
var qb=(b,a,c)=>{if(a===c)return b;if(void 0===c.Aa)return null;b=qb(b,a,c.Aa);return null===b?null:c.bb(b)},rb=(b,a)=>{a=Qa(b,a);return Pa[a]},sb=(b,a)=>{if(!a.ya||!a.va)throw new ab("makeClassHandle requires ptr and ptrType");if(!!a.Fa!==!!a.Ca)throw new ab("Both smartPtrType and smartPtr must be specified");a.count={value:1};return Q(Object.create(b,{ua:{value:a,writable:!0}}))};
function tb(b,a,c,d,e,f,h,g,l,m,k){this.name=b;this.wa=a;this.Qa=c;this.Oa=d;this.Pa=e;this.kb=f;this.pb=h;this.Ya=g;this.Sa=l;this.lb=m;this.Ha=k;e||void 0!==a.Aa?this.za=ob:(this.za=d?nb:pb,this.Ba=null)}var ub=(b,a)=>{if(!n.hasOwnProperty(b))throw new ab("Replacing nonexistent public symbol");n[b]=a;n[b].Ia=void 0},vb=[],U=b=>{var a=vb[b];a||(vb[b]=a=wb.get(b));return a},V=(b,a)=>{b=M(b);var c=U(a);if("function"!=typeof c)throw new H(`unknown function pointer with signature ${b}: ${a}`);return c};
class xb extends Error{}var W=(b,a)=>{function c(f){e[f]||N[f]||($a[f]?$a[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new xb(`${b}: `+d.map(Sa).join([", "]));};function yb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].Ba)return!0;return!1}
function zb(b,a,c,d,e,f){var h=a.length;if(2>h)throw new H("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==a[1]&&null!==c,l=yb(a);c=!a[0].Wa;var m=a[0],k=a[1];d=[b,Na,d,e,Ya,m.xa.bind(m),k?.za.bind(k)];for(e=2;e<h;++e)m=a[e],d.push(m.za.bind(m));if(!l)for(e=g?1:2;e<a.length;++e)null!==a[e].Ba&&d.push(a[e].Ba);l=yb(a);e=a.length-2;k=[];m=["fn"];g&&m.push("thisWired");for(h=0;h<e;++h)k.push(`arg${h}`),m.push(`arg${h}Wired`);k=k.join(",");m=m.join(",");
k=`return function (${k}) {\n`;l&&(k+="var destructors = [];\n");var r=l?"destructors":"null",p="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");g&&(k+=`var thisWired = toClassParamWire(${r}, this);\n`);for(h=0;h<e;++h){var t=`toArg${h}Wire`;k+=`var arg${h}Wired = ${t}(${r}, arg${h});\n`;p.push(t)}k+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(l)k+="runDestructors(destructors);\n";else for(h=g?1:2;h<a.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",
null!==a[h].Ba&&(k+=`${f}_dtor(${f});\n`,p.push(`${f}_dtor`));c&&(k+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(p,k+"}\n"))(...d);return La(b,a)}
var Ab=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(D[a+4*d>>2]);return c},Bb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},Cb=(b,a,c)=>{if(!(b instanceof Object))throw new H(`${c} with invalid "this": ${b}`);if(!(b instanceof a.wa.constructor))throw new H(`${c} incompatible with "this" of type ${b.constructor.name}`);if(!b.ua.va)throw new H(`cannot call emscripten binding method ${c} on deleted object`);return lb(b.ua.va,b.ua.ya.wa,a.wa)},Db=b=>{9<b&&0===--G[b+1]&&(G[b]=void 0,Ma.push(b))},
Eb={name:"emscripten::val",xa:b=>{var a=J(b);Db(b);return a},za:(b,a)=>K(a),Da:Za,Ba:null},Fb=(b,a,c)=>{switch(a){case 1:return c?function(d){return this.xa(w[d])}:function(d){return this.xa(x[d])};case 2:return c?function(d){return this.xa(y[d>>1])}:function(d){return this.xa(z[d>>1])};case 4:return c?function(d){return this.xa(A[d>>2])}:function(d){return this.xa(D[d>>2])};default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Hb=(b,a)=>{switch(a){case 4:return function(c){return this.xa(oa[c>>
2])};case 8:return function(c){return this.xa(pa[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},Ib=(b,a,c)=>{var d=x;if(0<c){c=a+c-1;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);if(127>=f){if(a>=c)break;d[a++]=f}else if(2047>=f){if(a+1>=c)break;d[a++]=192|f>>6;d[a++]=128|f&63}else if(65535>=f){if(a+2>=c)break;d[a++]=224|f>>12;d[a++]=128|f>>6&63;d[a++]=128|f&63}else{if(a+3>=c)break;d[a++]=240|f>>18;d[a++]=128|f>>12&63;d[a++]=128|f>>6&63;d[a++]=128|f&63;e++}}d[a]=0}},
Jb=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);127>=d?a++:2047>=d?a+=2:55296<=d&&57343>=d?(a+=4,++c):a+=3}return a},Kb=globalThis.TextDecoder&&new TextDecoder,Lb=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},Mb=(b=0,a,c)=>{var d=x;a=Lb(d,b,a,c);if(16<a-b&&d.buffer&&Kb)return Kb.decode(d.subarray(b,a));for(c="";b<a;){var e=d[b++];if(e&128){var f=d[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var h=d[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<
18|f<<12|h<<6|d[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Nb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,Ob=(b,a,c)=>{b>>=1;a=Lb(z,b,a/2,c);if(16<a-b&&Nb)return Nb.decode(z.subarray(b,a));for(c="";b<a;++b)c+=String.fromCharCode(z[b]);return c},Pb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)y[a>>1]=b.charCodeAt(e),a+=2;y[a>>1]=
0;return a-d},Qb=b=>2*b.length,Rb=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var f=D[b+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Sb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);65535<f&&e++;A[a>>2]=f;a+=4;if(a+4>c)break}A[a>>2]=0;return a-d},Tb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Ub=0,Vb=[],Wb=b=>{var a=Vb.length;Vb.push(b);return a},Xb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d)c[d]=
Ta(D[a+4*d>>2],`parameter ${d}`);return c},Yb=(b,a,c)=>{var d=[];b=b(d,c);d.length&&(D[a>>2]=K(d));return b},Zb={},$b=b=>{var a=Zb[b];return void 0===a?M(b):a},ac={},bc=b=>{la=b;Fa||0<Ub||(n.onExit?.(b),ka=!0);da(b,new Aa(b))},cc=b=>{if(!ka)try{b()}catch(a){a instanceof Aa||"unwind"==a||da(1,a)}finally{if(!(Fa||0<Ub))try{la=b=la,bc(b)}catch(a){a instanceof Aa||"unwind"==a||da(1,a)}}},ec=(b,a,c,d)=>{var e={string:m=>{var k=0;if(null!==m&&void 0!==m&&0!==m){k=Jb(m)+1;var r=dc(k);Ib(m,r,k);k=r}return k},
array:m=>{var k=dc(m.length);w.set(m,k);return k}};b=n["_"+b];var f=[],h=0;if(d)for(var g=0;g<d.length;g++){var l=e[c[g]];l?(0===h&&(h=X()),f[g]=l(d[g])):f[g]=d[g]}c=b(...f);return c=function(m){0!==h&&Y(h);return"string"===a?m?Mb(m):"":"boolean"===a?!!m:m}(c)};
(()=>{let b=fb.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof fb&&c instanceof fb))return!1;var d=this.ua.ya.wa,e=this.ua.va;c.ua=c.ua;var f=c.ua.ya.wa;for(c=c.ua.va;d.Aa;)e=d.Ma(e),d=d.Aa;for(;f.Aa;)c=f.Ma(c),f=f.Aa;return d===f&&e===c},clone:function(){this.ua.va||db(this);if(this.ua.Ka)return this.ua.count.value+=1,this;var c=Q,d=Object,e=d.create,f=Object.getPrototypeOf(this),h=this.ua;c=c(e.call(d,f,{ua:{value:{count:h.count,La:h.La,Ka:h.Ka,va:h.va,ya:h.ya,Ca:h.Ca,Fa:h.Fa}}}));
c.ua.count.value+=1;c.ua.La=!1;return c},["delete"](){this.ua.va||db(this);if(this.ua.La&&!this.ua.Ka)throw new H("Object already scheduled for deletion");Ua(this);var c=this.ua;--c.count.value;0===c.count.value&&(c.Ca?c.Fa.Ha(c.Ca):c.ya.wa.Ha(c.va));this.ua.Ka||(this.ua.Ca=void 0,this.ua.va=void 0)},isDeleted:function(){return!this.ua.va},deleteLater:function(){this.ua.va||db(this);if(this.ua.La&&!this.ua.Ka)throw new H("Object already scheduled for deletion");eb.push(this);this.ua.La=!0;return this}});
const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(tb.prototype,{fb(b){this.Ya&&(b=this.Ya(b));return b},Ta(b){this.Ha?.(b)},Da:Za,xa:function(b){function a(){return this.Pa?sb(this.wa.Ga,{ya:this.kb,va:c,Fa:this,Ca:b}):sb(this.wa.Ga,{ya:this,va:b})}var c=this.fb(b);if(!c)return this.Ta(b),null;var d=rb(this.wa,c);if(void 0!==d){if(0===d.ua.count.value)return d.ua.va=c,d.ua.Ca=b,d.clone();d=d.clone();this.Ta(b);return d}d=this.wa.eb(c);d=gb[d];if(!d)return a.call(this);d=this.Oa?d.ab:d.pointerType;var e=qb(c,this.wa,d.wa);return null===
e?a.call(this):this.Pa?sb(d.wa.Ga,{ya:d,va:e,Fa:this,Ca:b}):sb(d.wa.Ga,{ya:d,va:e})}});n.noExitRuntime&&(Fa=n.noExitRuntime);n.printErr&&(q=n.printErr);n.wasmBinary&&(u=n.wasmBinary);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();n.ccall=ec;n.cwrap=(b,a,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==a&&e&&!d?n["_"+b]:(...f)=>ec(b,a,c,f,d)};
var Ra,fc,gc,O,Z,F,Y,dc,X,hc,ic,Ja,jc,ua,wb,xc={A:b=>{var a=new Ia(b);0==w[a.va+12]&&(w[a.va+12]=1,Ha--);w[a.va+13]=0;Ga.push(a);return jc(b)},V:()=>{Z(0,0);var b=Ga.pop();ic(b.Ua);E=0},a:()=>Ka([]),i:b=>Ka([b]),W:()=>{var b=Ga.pop();b||va("no exception to throw");var a=b.Ua;0==w[b.va+13]&&(Ga.push(b),w[b.va+13]=1,w[b.va+12]=0,Ha++);hc(a);E=a;throw E;},o:(b,a,c)=>{var d=new Ia(b);D[d.va+16>>2]=0;D[d.va+4>>2]=a;D[d.va+8>>2]=c;hc(b);E=b;Ha++;throw E;},g:b=>{E||=b;throw E;},M:()=>va(""),T:(b,a,c)=>{b=
M(b);a=Ta(a,"wrapper");c=J(c);var d=a.wa,e=d.Ga,f=d.Aa.Ga,h=d.Aa.constructor;b=La(b,function(...g){for(var l of d.Aa.Xa)if(this[l]===f[l])throw new Oa(`Pure virtual function ${l} must be implemented in JavaScript`);Object.defineProperty(this,"__parent",{value:e});this.__construct(...g)});e.__construct=function(...g){if(this===e)throw new H("Pass correct 'this' to __construct");g=h.implement(this,...g);Ua(g);var l=g.ua;g.notifyOnDestruction();l.Ka=!0;Object.defineProperties(this,{ua:{value:l}});Q(this);
g=l.va;g=Qa(d,g);if(Pa.hasOwnProperty(g))throw new H(`Tried to register registered instance: ${g}`);Pa[g]=this};e.__destruct=function(){if(this===e)throw new H("Pass correct 'this' to __destruct");Ua(this);var g=this.ua.va;g=Qa(d,g);if(Pa.hasOwnProperty(g))delete Pa[g];else throw new H(`Tried to unregister unregistered instance: ${g}`);};b.prototype=Object.create(e);Object.assign(b.prototype,c);return K(b)},Y:b=>{var a=Xa[b];delete Xa[b];var c=a.Sa,d=a.Ha,e=a.Va,f=e.map(h=>h.ib).concat(e.map(h=>h.nb));
T([b],f,h=>{var g={},l,m;for([l,m]of e.entries()){const k=h[l],r=m.gb,p=m.hb,t=h[l+e.length],v=m.mb,B=m.ob;g[m.cb]={read:I=>k.xa(r(p,I)),write:(I,L)=>{var C=[];v(B,I,t.za(C,L));Ya(C)},optional:k.optional}}return[{name:a.name,xa:k=>{var r={},p;for(p in g)r[p]=g[p].read(k);d(k);return r},za:(k,r)=>{for(var p in g)if(!(p in r||g[p].optional))throw new TypeError(`Missing field: "${p}"`);var t=c();for(p in g)g[p].write(t,r[p]);null!==k&&k.push(d,t);return t},Da:Za,Ba:d}]})},C:(b,a,c,d,e)=>{a=M(a);d=0n===
d;let f=h=>h;if(d){const h=8*c;f=g=>BigInt.asUintN(h,g);e=f(e)}S(b,{name:a,xa:f,za:(h,g)=>{"number"==typeof g&&(g=BigInt(g));return g},Da:cb(a,c,!d),Ba:null})},R:(b,a,c,d)=>{a=M(a);S(b,{name:a,xa:function(e){return!!e},za:function(e,f){return f?c:d},Da:function(e){return this.xa(x[e])},Ba:null})},q:(b,a,c,d,e,f,h,g,l,m,k,r,p)=>{k=M(k);f=V(e,f);g&&=V(h,g);m&&=V(l,m);p=V(r,p);var t=jb(k);ib(t,function(){W(`Cannot construct ${k} due to unbound types`,[d])});T([b,a,c],d?[d]:[],v=>{v=v[0];if(d){var B=
v.wa;var I=B.Ga}else I=fb.prototype;v=La(k,function(...Va){if(Object.getPrototypeOf(this)!==L)throw new H(`Use 'new' to construct ${k}`);if(void 0===C.Ja)throw new H(`${k} has no accessible constructor`);var Gb=C.Ja[Va.length];if(void 0===Gb)throw new H(`Tried to invoke ctor of ${k} with invalid number of parameters (${Va.length}) - expected (${Object.keys(C.Ja).toString()}) parameters instead!`);return Gb.apply(this,Va)});var L=Object.create(I,{constructor:{value:v}});v.prototype=L;var C=new kb(k,
v,L,p,B,f,g,m);if(C.Aa){var P;(P=C.Aa).Na??(P.Na=[]);C.Aa.Na.push(C)}B=new tb(k,C,!0,!1,!1);P=new tb(k+"*",C,!1,!1,!1);I=new tb(k+" const*",C,!1,!0,!1);gb[b]={pointerType:P,ab:I};ub(t,v);return[B,P,I]})},D:(b,a,c,d,e,f,h,g)=>{var l=Ab(c,d);a=M(a);a=Bb(a);f=V(e,f);T([],[b],m=>{function k(){W(`Cannot call ${r} due to unbound types`,l)}m=m[0];var r=`${m.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);var p=m.wa.constructor;void 0===p[a]?(k.Ia=c-1,p[a]=k):(hb(p,a,r),p[a].Ea[c-1]=k);T([],l,
t=>{t=[t[0],null].concat(t.slice(1));t=zb(r,t,null,f,h,g);void 0===p[a].Ea?(t.Ia=c-1,p[a]=t):p[a].Ea[c-1]=t;if(m.wa.Na)for(const v of m.wa.Na)v.constructor.hasOwnProperty(a)||(v.constructor[a]=t);return[]});return[]})},z:(b,a,c,d,e,f)=>{var h=Ab(a,c);e=V(d,e);T([],[b],g=>{g=g[0];var l=`constructor ${g.name}`;void 0===g.wa.Ja&&(g.wa.Ja=[]);if(void 0!==g.wa.Ja[a-1])throw new H(`Cannot register multiple constructors with identical number of parameters (${a-1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
g.wa.Ja[a-1]=()=>{W(`Cannot construct ${g.name} due to unbound types`,h)};T([],h,m=>{m.splice(1,0,null);g.wa.Ja[a-1]=zb(l,m,null,e,f);return[]});return[]})},n:(b,a,c,d,e,f,h,g,l)=>{var m=Ab(c,d);a=M(a);a=Bb(a);f=V(e,f);T([],[b],k=>{function r(){W(`Cannot call ${p} due to unbound types`,m)}k=k[0];var p=`${k.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);g&&k.wa.Xa.push(a);var t=k.wa.Ga,v=t[a];void 0===v||void 0===v.Ea&&v.className!==k.name&&v.Ia===c-2?(r.Ia=c-2,r.className=k.name,t[a]=
r):(hb(t,a,p),t[a].Ea[c-2]=r);T([],m,B=>{B=zb(p,B,k,f,h,l);void 0===t[a].Ea?(B.Ia=c-2,t[a]=B):t[a].Ea[c-2]=B;return[]});return[]})},U:(b,a,c,d,e,f,h,g,l,m)=>{a=M(a);e=V(d,e);T([],[b],k=>{k=k[0];var r=`${k.name}.${a}`,p={get(){W(`Cannot access ${r} due to unbound types`,[c,h])},enumerable:!0,configurable:!0};p.set=l?()=>W(`Cannot access ${r} due to unbound types`,[c,h]):()=>{throw new H(r+" is a read-only property");};Object.defineProperty(k.wa.Ga,a,p);T([],l?[c,h]:[c],t=>{var v=t[0],B={get(){var L=
Cb(this,k,r+" getter");return v.xa(e(f,L))},enumerable:!0};if(l){l=V(g,l);var I=t[1];B.set=function(L){var C=Cb(this,k,r+" setter"),P=[];l(m,C,I.za(P,L));Ya(P)}}Object.defineProperty(k.wa.Ga,a,B);return[]});return[]})},O:b=>S(b,Eb),$:(b,a,c,d,e)=>{a=M(a);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function h(){}h.values={};S(b,{name:a,constructor:h,valueType:e,xa:function(g){return this.constructor.values[g]},za:(g,l)=>l.value,Da:Fb(a,c,d),Ba:null});ib(a,h);break;case "number":var f=
{};S(b,{name:a,Ra:f,valueType:e,xa:g=>g,za:(g,l)=>l,Da:Fb(a,c,d),Ba:null});ib(a,f);delete n[a].Ia;break;case "string":f={},S(b,{name:a,$a:{},Za:{},Ra:f,valueType:e,xa:function(g){return this.Za[g]},za:function(g,l){return this.$a[l]},Da:Fb(a,c,d),Ba:null}),ib(a,f),delete n[a].Ia}},r:(b,a,c)=>{var d=Ta(b,"enum");a=M(a);switch(d.valueType){case "object":b=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:La(`${d.name}_${a}`,function(){})}});b.values[c]=d;b[a]=
d;break;case "number":d.Ra[a]=c;break;case "string":d.$a[a]=c,d.Za[c]=a,d.Ra[a]=a}},B:(b,a,c)=>{a=M(a);S(b,{name:a,xa:d=>d,za:(d,e)=>e,Da:Hb(a,c),Ba:null})},m:(b,a,c,d,e)=>{a=M(a);let f=g=>g;if(0===d){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}S(b,{name:a,xa:f,za:(g,l)=>l,Da:cb(a,c,0!==d),Ba:null})},k:(b,a,c)=>{function d(f){return new e(w.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=M(c);S(b,
{name:c,xa:d,Da:d},{jb:!0})},E:(b,a,c,d,e,f,h,g,l,m,k,r)=>{c=M(c);f=V(e,f);g=V(h,g);m=V(l,m);r=V(k,r);T([b],[a],p=>{p=p[0];return[new tb(c,p.wa,!1,!1,!0,p,d,f,g,m,r)]})},P:(b,a)=>{a=M(a);S(b,{name:a,xa(c){var d=(d=c+4)?Mb(d,D[c>>2],!0):"";O(c);return d},za(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new H("Cannot pass non-string to std::string");var f=e?Jb(d):d.length;var h=fc(4+f+1),g=h+4;D[h>>2]=f;e?Ib(d,
g,f+1):x.set(d,g);null!==c&&c.push(O,h);return h},Da:Za,Ba(c){O(c)}})},y:(b,a,c)=>{c=M(c);if(2===a){var d=Ob;var e=Pb;var f=Qb}else d=Rb,e=Sb,f=Tb;S(b,{name:c,xa:h=>{var g=d(h+4,D[h>>2]*a,!0);O(h);return g},za:(h,g)=>{if("string"!=typeof g)throw new H(`Cannot pass non-string to C++ string type ${c}`);var l=f(g),m=fc(4+l+a);D[m>>2]=l/a;e(g,m+4,l+a);null!==h&&h.push(O,m);return m},Da:Za,Ba(h){O(h)}})},_:(b,a,c,d,e,f)=>{Xa[b]={name:M(a),Sa:V(c,d),Ha:V(e,f),Va:[]}},Z:(b,a,c,d,e,f,h,g,l,m)=>{Xa[b].Va.push({cb:M(a),
ib:c,gb:V(d,e),hb:f,nb:h,mb:V(g,l),ob:m})},S:(b,a)=>{a=M(a);S(b,{Wa:!0,name:a,xa:()=>{},za:()=>{}})},K:()=>{Fa=!1;Ub=0},t:(b,a,c)=>{var [d,...e]=Xb(b,a);a=d.za.bind(d);var f=e.map(l=>l.Da.bind(l));b--;var h={toValue:J};b=f.map((l,m)=>{var k=`argFromPtr${m}`;h[k]=l;return`${k}(args${m?"+"+8*m:""})`});switch(c){case 0:var g="toValue(handle)";break;case 2:g="new (toValue(handle))";break;case 3:g="";break;case 1:h.getStringOrSymbol=$b,g="toValue(handle)[getStringOrSymbol(methodName)]"}g+=`(${b})`;d.Wa||
(h.toReturnWire=a,h.emval_returnValue=Yb,g=`return emval_returnValue(toReturnWire, destructorsRef, ${g})`);g=`return function (handle, methodName, destructorsRef, args) {\n${g}\n}`;c=(new Function(Object.keys(h),g))(...Object.values(h));g=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return Wb(La(g,c))},aa:Db,ca:b=>{if(!b)return K(globalThis);b=$b(b);return K(globalThis[b])},F:(b,a)=>{b=J(b);a=J(a);return K(b[a])},v:b=>{9<b&&(G[b+1]+=1)},s:(b,a,c,d,e)=>Vb[b](a,c,d,e),G:()=>K([]),da:b=>K($b(b)),
X:()=>K({}),H:b=>{var a=J(b);Ya(a);Db(b)},Q:(b,a,c)=>{b=J(b);a=J(a);c=J(c);b[a]=c},ba:b=>{b=J(b);return K(typeof b)},L:(b,a)=>{ac[b]&&(clearTimeout(ac[b].id),delete ac[b]);if(!a)return 0;var c=setTimeout(()=>{delete ac[b];cc(()=>gc(b,performance.now()))},a);ac[b]={id:c,qb:a};return 0},N:b=>{var a=x.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(b,d)/65536))-ua.buffer.byteLength+65535)/65536|
0;try{ua.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},x:kc,l:lc,w:mc,j:nc,h:oc,d:pc,f:qc,c:rc,b:sc,e:tc,p:uc,I:vc,u:wc,J:bc};function qc(b){var a=X();try{U(b)()}catch(c){Y(a);if(c!==c+0)throw c;Z(1,0)}}function tc(b,a,c,d){var e=X();try{U(b)(a,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function sc(b,a,c){var d=X();try{U(b)(a,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function pc(b,a,c,d){var e=X();try{return U(b)(a,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}
function oc(b,a,c){var d=X();try{return U(b)(a,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function vc(b,a,c,d,e,f,h,g,l){var m=X();try{U(b)(a,c,d,e,f,h,g,l)}catch(k){Y(m);if(k!==k+0)throw k;Z(1,0)}}function nc(b,a){var c=X();try{return U(b)(a)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function kc(b,a){var c=X();try{return U(b)(a)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function mc(b){var a=X();try{return U(b)()}catch(c){Y(a);if(c!==c+0)throw c;Z(1,0)}}
function lc(b,a,c,d,e,f){var h=X();try{return U(b)(a,c,d,e,f)}catch(g){Y(h);if(g!==g+0)throw g;Z(1,0)}}function rc(b,a){var c=X();try{U(b)(a)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function uc(b,a,c,d,e){var f=X();try{U(b)(a,c,d,e)}catch(h){Y(f);if(h!==h+0)throw h;Z(1,0)}}function wc(b,a,c,d,e,f,h,g,l,m,k){var r=X();try{U(b)(a,c,d,e,f,h,g,l,m,k)}catch(p){Y(r);if(p!==p+0)throw p;Z(1,0)}}var yc;
yc=await (async function(){function b(c){c=yc=c.exports;Ra=c.ga;fc=n._malloc=c.ha;gc=c.ia;O=n._free=c.ka;Z=c.la;F=c.ma;Y=c.na;dc=c.oa;X=c.pa;hc=c.qa;ic=c.ra;Ja=c.sa;jc=c.ta;ua=c.ea;wb=c.ja;ta();return yc}var a={a:xc};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(a,(d,e)=>{c(b(d,e))})});wa??=n.locateFile?n.locateFile?n.locateFile("sql_engine.wasm",fa):fa+"sql_engine.wasm":(new URL("sql_engine.wasm",import.meta.url)).href;return b((await za(a)).instance)}());
(function(){function b(){n.calledRun=!0;if(!ka){sa=!0;yc.fa();ma?.(n);n.onRuntimeInitialized?.();if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;){var a=n.postRun.shift();Ca.push(a)}Ba(Ca)}}if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Ea();Ba(Da);n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);b()},1)):b()})();sa?moduleRtn=n:moduleRtn=new Promise((b,a)=>{ma=b;na=a});
;return moduleRtn}export default Module;
